language: node_js
node_js:
  - 11.6.0
cache: npm

install:
  - npm install
  
script:
  - docker pull michelleamesquita/cucumber-bdd-ci
  - docker run -v $PWD/:/app/report/michelleamesquita/cucumber-bdd-ci

after_script:
  - bash ./telegram_notification.sh
